version: "3.1"
services:
  job:
    build: .
    container_name: notification_job
    volumes:
      - ./:/notification_job
    environment:
      - SERVICE_URL=http://192.168.1.3:5000
      - USERNAME=avieira
      - PASSWORD=123455
